version: '3'
services:
  schlepwise_local:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DATABASE_HOST: postgres
    ports:
      - 4000:4000
    volumes:
      - ./var/code
      - ./tmp/logs:/mnt/logs
    depends_on:
      - postgres
    command: 'sh /var/code/run.sh'


  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    volumes:
      - ./tmp/pg_data/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: schlepwise_local_user
      POSTGRES_PASSWORD: schlepwise_local_password
      POSTGRES_MULTIPLE_DATABASES: schlepwise
    ports:
      - 5432:5432
