"""Make households table

Revision ID: 73bfb10d7b5c
Revises: dc55a09f7405
Create Date: 2021-09-03 20:09:50.559735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bfb10d7b5c'
down_revision = 'dc55a09f7405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    op.add_column('users', sa.Column('household_id', sa.String(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(op.f('fk_users_household_id_households'), 'users', 'households', ['household_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_household_id_households'), 'users', type_='foreignkey')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'household_id')
    op.drop_table('households')
    # ### end Alembic commands ###
