"""users.household_id is non-null

Revision ID: b6a61ba88a3f
Revises: c558bbd99d75
Create Date: 2021-11-25 15:28:32.538255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a61ba88a3f'
down_revision = 'c558bbd99d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'household_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'household_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
