"""Make tasks and chores tables

Revision ID: c558bbd99d75
Revises: 73bfb10d7b5c
Create Date: 2021-11-25 12:23:27.674854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c558bbd99d75'
down_revision = '73bfb10d7b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_table('chores',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('requested_by_id', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_chores_household_id_households')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_chores_requested_by_id_users')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_chores_task_id_tasks')),
    sa.PrimaryKeyConstraint('task_id', 'household_id', 'requested_by_id', 'requested_at', name=op.f('pk_chores'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chores')
    op.drop_table('tasks')
    # ### end Alembic commands ###
